<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-10-28T21:28:56 IST" name="Default suite" finished-at="2020-10-28T21:29:15 IST" duration-ms="18855">
    <groups>
    </groups>
    <test started-at="2020-10-28T21:28:56 IST" name="Default test" finished-at="2020-10-28T21:29:15 IST" duration-ms="18855">
      <class name="RestAssured.TC001_APITest$RestTest">
        <test-method signature="APITestPositive()[pri:1, instance:RestAssured.TC001_APITest$RestTest@d4342c2]" started-at="2020-10-28T21:28:56 IST" name="APITestPositive" finished-at="2020-10-28T21:29:04 IST" duration-ms="8142" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- APITestPositive -->
        <test-method signature="APITestNegative()[pri:2, instance:RestAssured.TC001_APITest$RestTest@d4342c2]" started-at="2020-10-28T21:29:04 IST" name="APITestNegative" finished-at="2020-10-28T21:29:15 IST" duration-ms="10627" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [250] but found [244]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [250] but found [244]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at RestAssured.TC001_APITest$RestTest.APITestNegative(TC001_APITest.java:160)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- APITestNegative -->
      </class> <!-- RestAssured.TC001_APITest$RestTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
